spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users, /users/**
          filters:
            - AuthenticationFilter

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels, /hotels/**,/staffs/**
          filters:
            - AuthenticationFilter

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings, /ratings/**
          filters:
            - AuthenticationFilter

        - id: AUTHSERVICE
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/login, /login/**, /api/users ,/api/users/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  retry:
    instances:
      authServiceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - com.example.gateway.exception.InvalidTokenException

  circuitbreaker:
    instances:
      authServiceCB:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - com.example.gateway.exception.InvalidTokenException