spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users, /users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels, /hotels/**,/staffs/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings, /ratings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost