server:
  port: 8081


spring:
    datasource:
      url: jdbc:mysql://localhost:3306/microservices
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


    config:
      import: optional:configserver:http://localhost:8085

#actuator Config

management:
  health:
    circuit breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

#Resilience config

resilience4j:
  circuitbreaker:
    instances:
      userRatingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50   #Percentage 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

#Retry Config

  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        wait-duration:
          seconds: 2
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
          - java.net.SocketTimeoutException
          - java.lang.IllegalStateException

        ignore-exceptions:
          - com.user.service.UserService.Exceptions.ResourceNotFoundException
          - org.springframework.web.client.HttpClientErrorException


  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s


logging:
  level:
    io.github.resilience4j.retry: DEBUG