spring:
  application:
    name: RatingService
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Microservices-hotel

#Importing data from the Config Server
  config:
    import: optional:configserver:http://localhost:8085

server:
  port: 9093

